refactor: update stack with component-rollup-config
ovh-ux/ng-tail-logs pull request #14
Opened 2018-12-14 10:30 UTC by cbourgois

##

### Description of the Change

* Remove documentation & tests
* replace grunt by rollup (using `@ovh-ux/component-rollup-config`)
* Fix dependencies

BREAKING CHANGE: module name is now `ngTailLogs` and package is scoped in `@ovh-ux`

    Before:

        import 'ovh-angular-tail-logs';
        angular.module('myModule', ['ovh-angular-tail-logs'])

    After:

        import '@ovh-ux/ng-tail-logs';
        angular.module('myModule', ['ngTailLogs'])

d12d677 — refactor: update stack with component-rollup-config

ref:

/cc @jleveugle @frenautvh @antleblanc

2018-12-14 10:45 UTC, FredericEspiau submitted a review, later dismissed

2018-12-14 11:03 UTC, antleblanc requested changes

2018-12-14 11:03 UTC, antleblanc commented on README.md
> +> OVH ANgular Tail Logs Module
```suggestion
> OVH Angular Tail Logs Module
```

2018-12-14 11:03 UTC, antleblanc commented on README.md
> +[![Downloads](https://badgen.net/npm/dt/@ovh-ux/ng-tail-logs)](https://npmjs.com/package/@ovh-ux/ng-tail-logs) [![Dependencies](https://badgen.net/david/dep/ovh-ux/@ovh-ux/ng-tail-logs)](https://npmj
```suggestion
[![Downloads](https://badgen.net/npm/dt/@ovh-ux/ng-tail-logs)](https://npmjs.com/package/@ovh-ux/ng-tail-logs) [![Dependencies](https://badgen.net/david/dep/ovh-ux/ng-tail-logs)](https://npmjs.com/package/@ovh-ux/ng-tail-logs?activeTab=dependencies) [![Dev Dependencies](https://badgen.net/david/dev/ovh-ux/ng-tail-logs)](https://npmjs.com/package/@ovh-ux/ng-tail-logs?activeTab=dependencies) [![Gitter](https://badgen.net/badge/gitter/ovh-ux/blue?icon=gitter)](https://gitter.im/ovh/ux)
```

2018-12-14 11:03 UTC, antleblanc commented on README.md
>  ```javascript
You can use the shorthand:

```txt
```js
```

2018-12-14 11:03 UTC, antleblanc commented on package.json
> +  "repository": "ovh-ux/ovh-angular-tail-logs",
The repository have to be renamed as well.

```suggestion
  "repository": "ovh-ux/ng-tail-logs",
```

2018-12-14 11:03 UTC, antleblanc commented on rollup.config.js
> +export default [
Provide config.es() by default?

And:

```js
if (process.env.BUILD === 'production') {
  outputs.push(config.cjs());
  outputs.push(congif.umd({…})
}
```

2018-12-14 12:41 UTC, cbourgois commented on README.md
> +> OVH ANgular Tail Logs Module
Done

2018-12-23 09:00 UTC, jleveugle commented
Hello @cbourgois,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

2018-12-23 09:00 UTC, closed without merging